### ISSUE TITLE
您好ERROR: can't find musl-libc debug symbols

### ISSUE THREAD

**Issue by tangzichengcc** [xf1les/muslheap#1]
ERROR: can't find musl-libc debug symbols!

muslheap.py requires musl-libc 1.2.1+ with debug symbols installed.

Either debug symbols are not installed or broken, or a libc without mallocng support (e.g. musl-libc < 1.2.1 or glibc) is used.
但是我已经安装了符号文件了,而且musl的版本也是符合的,请问有办法解决吗

**Comment by xf1les** [comment]
麻烦贴一下你目前所用的发行版、musl libc 以及其调试符号的软件包版本。可以的话，最好也贴一下从启动到 muslheap 报错的 gdb 输出日志（截图也没问题）。

不确定是安装的调试符号包有问题，或者是 gdb 没有加载到调试符号。

之所以会报错，因为调用 muslheap 命令前，首先会[检查](https://github.com/xf1les/muslheap/blob/10ab9e71d79cf375825f47b10793a13c8a2849bf/muslheap.py#L88) gdb 是否存在 `struct __malloc_context`这个结构体的调试符号。若无则视为用户没有提供调试符号。

**Comment by tangzichengcc** [comment]
Starting program: /root/musl-1.2.2/test

ubuntu 20.04 LTS 22.04LTS都试过了
Linux vultr 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
调试符号这个 musl-dbgsym_1.2.2-1_amd64.ddeb
musl下载的这个http://ftp.de.debian.org/debian/pool/main/m/musl/musl_1.2.2-1_amd64.deb
参考的这一篇博客 https://bbs.kanxue.com/thread-274629.htm
struct __malloc_context确实不存在

输出日志
Temporary breakpoint 1, main () at demo.c:11
11	int main() {
Not stopped at any breakpoint; argument ignored.
Continuing.

Program received signal SIGINT, Interrupt.
0x00007ffff7fc2658 in __cp_end () from ./lib/libc.so
ERROR: can't find musl-libc debug symbols!

muslheap.py requires musl-libc 1.2.1+ with debug symbols installed.

Either debug symbols are not installed or broken, or a libc without mallocng support (e.g. musl-libc < 1.2.1 or glibc) is used.

**Comment by tangzichengcc** [comment]
sudo dpkg -i musl_1.2.2-1_amd64.deb
sudo dpkg -i musl-dbgsym_1.2.2-1_amd64.ddeb
您好,可以了,需要这两个都安装才行
